# Generated by Django 5.1.6 on 2025-03-06 02:08

import MSRV.apps.user.models_folder.user
import MSRV.apps.utils.enum_type
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('is_staff', models.BooleanField(blank=True, default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('soft_delete', models.BooleanField(blank=True, default=False)),
                ('verify_code', models.CharField(blank=True, max_length=10)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('ADMIN', 'ADMIN'), ('TEACHER', 'TEACHER')], default=MSRV.apps.utils.enum_type.SystemRoleEnum['TEACHER'], max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', MSRV.apps.user.models_folder.user.CustomUserManager()),
            ],
        ),
    ]
