# Generated by Django 5.1.6 on 2025-03-06 04:50

import MSRV.apps.utils.enum_type
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('TS', 'TS'), ('THS', 'THS'), ('PGS', 'PGS'), ('GS', 'GS')], default=MSRV.apps.utils.enum_type.DegreeEnum['TS'], max_length=30)),
                ('department', models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('LEGAL', 'LEGAL'), ('SALES', 'SALES'), ('TOURISM', 'TOURISM'), ('FINANCE', 'FINANCE'), ('MARKETING', 'MARKETING'), ('OPERATIONS', 'OPERATIONS'), ('ENGINEERING', 'ENGINEERING'), ('ARCHITECTURE', 'ARCHITECTURE'), ('ADMINISTRATION', 'ADMINISTRATION'), ('GRAPHIC_DESIGN', 'GRAPHIC_DESIGN'), ('CUSTOMER_SERVICE', 'CUSTOMER_SERVICE'), ('FOREIGN_LANGUAGES', 'FOREIGN_LANGUAGES'), ('INFORMATION_TECHNOLOGY', 'INFORMATION_TECHNOLOGY')], default=MSRV.apps.utils.enum_type.DepartmentEnum['INFORMATION_TECHNOLOGY'], max_length=30)),
                ('country', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('nation', models.CharField(max_length=64)),
                ('nationality', models.CharField(max_length=64)),
                ('religion', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
