# Generated by Django 5.1.6 on 2025-03-06 06:56

from django.db import migrations

def load_sql_from_file(apps, schema_editor):
    print("Create user profile Apps: ", apps)
    with open('MSRV/apps/user/core/create_use_profile_trigger.sql', 'r') as file:
        sql_script = file.read()
    schema_editor.execute(sql_script)

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.RunPython(load_sql_from_file),
    ]
