# Generated by Django 5.1.6 on 2025-04-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscientificresearch',
            name='point',
            field=models.FloatField(default=0),
        ),
    ]
