# Generated by Django 5.1.6 on 2025-04-18 10:09

import MSRV.apps.utils.enum_type
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userscientificresearch_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='base_point',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(choices=[('TS', 'TS'), ('THS', 'THS'), ('PGS', 'PGS'), ('GS', 'GS'), ('UN_TS_III', 'UN_TS_III'), ('TS_III', 'TS_III'), ('UN_TS_II', 'UN_TS_II'), ('TS_II', 'TS_II')], default=MSRV.apps.utils.enum_type.DegreeEnum['TS'], max_length=30),
        ),
    ]
