# Generated by Django 5.1.6 on 2025-03-11 02:33

import MSRV.apps.utils.enum_type
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificResearchActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.CharField(choices=[('RESEARCH_PROJECTS', 'RESEARCH_PROJECTS'), ('ARTICLES_BOOKS', 'ARTICLES_BOOKS'), ('STUDENT_GUIDANCE', 'STUDENT_GUIDANCE'), ('WORKS_PUBLICATIONS', 'WORKS_PUBLICATIONS'), ('OTHER_ACTIVITIES', 'OTHER_ACTIVITIES')], default=MSRV.apps.utils.enum_type.GroupEnum['RESEARCH_PROJECTS'], max_length=50)),
                ('content', models.TextField()),
                ('conversion_time', models.IntegerField()),
                ('proof', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('input', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sr_activities',
            },
        ),
        migrations.CreateModel(
            name='ScientificResearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number_member', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('PROCESS', 'PROCESS'), ('COMPLETE', 'COMPLETE'), ('NOT_COMPLETED', 'NOT_COMPLETED'), ('DELETED', 'DELETED')], default=MSRV.apps.utils.enum_type.StatusSREnum['OPEN'], max_length=50)),
                ('level', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('banner', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sr_activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_research', to='sr_activities.scientificresearchactivity')),
            ],
            options={
                'db_table': 's_research',
            },
        ),
    ]
