# Generated by Django 5.1.6 on 2025-04-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sr_activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificresearch',
            name='time_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
