# Generated by Django 5.1.6 on 2025-04-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sr_activities', '0002_scientificresearch_time_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificresearch',
            name='banner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scientificresearch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scientificresearch',
            name='number_member',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
