# Generated by Django 5.1.6 on 2025-04-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sr_activities', '0003_alter_scientificresearch_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificresearch',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
