# Generated by Django 5.1.6 on 2025-04-02 08:32

import MSRV.apps.utils.enum_type
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sr_activities', '0002_scientificresearch_time_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('funding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('PASSED', 'PASSED'), ('NOT_PASSED', 'NOT_PASSED'), ('CANCELLED', 'CANCELLED')], default=MSRV.apps.utils.enum_type.StatusSPEnum['OPEN'], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('s_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_proposal', to='sr_activities.scientificresearch')),
            ],
            options={
                'db_table': 'sponsorship_proposal',
            },
        ),
    ]
